/** @typedef {import('./types.mjs').GameManifest} GameManifest */

/**
 * @param {GameManifest} m
 */
export function generateOperationGuide(m) {
  const reviewMonth = m.releasedAt.slice(0, 7);
  return `# ${m.title} — Operation Guide

**Slug:** \`${m.slug}\`  
**Category:** ${m.category}  
**Released:** ${m.releasedAt}  
**Generated by:** Content Factory

---

## 운영 체크 (5분)

| Check | Path | Expected |
| --- | --- | --- |
| Load | \`/games/${m.slug}\` | 200 |
| Featured | \`/admin/cms/featured\` → new_games | Active |
| Launch Event | \`/admin/cms/events\` | game_slug = ${m.slug} |
| NEW Badge | Home / games list | 7일 이내 |
| Analytics | \`/admin/analytics\` | Play +1 after test |

---

## 비활성화

1. \`/admin/cms/visibility\` → Hidden
2. \`/admin/flags\` → beta_games OFF (if used)

---

## Review Card

\`docs/reports/game-reviews/${m.slug}-${reviewMonth}.md\`
`;
}

/**
 * @param {GameManifest} m
 */
export function generateReviewCard(m) {
  const reviewMonth = m.releasedAt.slice(0, 7);
  const stars = m.difficulty === "EASY" ? "★★★☆☆" : "★★★★☆";
  return `# Game Review Card — ${m.title}

**Slug:** \`${m.slug}\`  
**Launch:** ${m.releasedAt}  
**Status:** PLACEHOLDER — D+7 데이터 입력

| KPI | D+0 | D+7 |
| --- | --- | --- |
| Play | | |
| Finish Rate | | |
| Retry | | |
| Favorite | | |

**PM Sign-off:** PENDING
`;
}

export { generateReviewCard as generateReviewCardPlaceholder };
