/** Playable slugs — keep in sync with apps/web/lib/playable-games.ts */
export const PLAYABLE_SLUGS = [
  "2048",
  "snake",
  "breakout",
  "arkanoid-dx",
  "memory",
  "minesweeper",
  "samegame",
  "maze-runner",
  "tank-battle",
  "galaxy-defender",
  "space-defender",
  "bubble-pop",
  "sudoku",
  "tic-tac-toe",
  "simon",
  "hangman",
  "color-match",
  "air-hockey",
  "tetris",
  "gold-miner",
  "space-impact",
  "stack-tower",
  "ball-sort",
  "color-sort",
  "penalty-shootout",
  "darts",
  "bubble-shooter",
  "merge-blocks",
  "connect4",
  "reversi",
  "gomoku",
  "bowling",
  "archery",
  "sliding-puzzle",
  "whack-a-mole",
  "chess",
  "checkers",
  "jigsaw",
  "mancala",
  "mini-golf",
  "billiards",
  "basketball",
  "table-tennis",
  "domino",
  "crossword",
  "chess960",
  "shuffleboard",
  "kakuro",
  "nonogram",
  "word-search",
] as const;

export type PlayableSlug = (typeof PLAYABLE_SLUGS)[number];

export const ADMIN_ROUTES = [
  "/admin",
  "/admin/analytics",
  "/admin/games",
  "/admin/cms",
  "/admin/cms/categories",
  "/admin/cms/banners",
  "/admin/cms/events",
  "/admin/cms/featured",
  "/admin/cms/notices",
  "/admin/cms/visibility",
  "/admin/cms/audit",
  "/admin/monitoring",
  "/admin/soft-launch",
  "/admin/seo",
  "/admin/settings",
  "/admin/flags",
  "/admin/reports",
] as const;

export const STATIC_ROUTES = [
  "/",
  "/games",
  "/profile",
  "/favorites",
  "/search",
  "/about",
  "/contact",
  "/privacy",
  "/terms",
  "/categories/puzzle",
  "/categories/arcade",
  "/sitemap.xml",
  "/robots.txt",
] as const;
