-- Sprint 15 RC1: nostalgia notes for games missing copy (Operator apply)
-- Safe to re-run: only updates rows where nostalgia_note IS NULL

update public.games set nostalgia_note = '숫자를 밀어 합치던 그 손맛, 다시 한 번.' where slug = '2048' and nostalgia_note is null;
update public.games set nostalgia_note = '피처폰 시절 뱀 게임의 그 중독성을 브라우저에서.' where slug = 'snake' and nostalgia_note is null;
update public.games set nostalgia_note = '벽돌 깨기 한 판 더 — 오락실의 클래식.' where slug = 'breakout' and nostalgia_note is null;
update public.games set nostalgia_note = '아케이드 슈팅의 정수, 우주를 지키던 그날.' where slug = 'arkanoid-dx' and nostalgia_note is null;
update public.games set nostalgia_note = '카드 짝 맞추기로 기억력을 키우던 두뇌 게임.' where slug = 'memory' and nostalgia_note is null;
update public.games set nostalgia_note = '숫자 힌트로 지뢰를 피하던 논리의 즐거움.' where slug = 'minesweeper' and nostalgia_note is null;
update public.games set nostalgia_note = '같은 색을 터뜨리던 클릭 한 방의 쾌감.' where slug = 'samegame' and nostalgia_note is null;
update public.games set nostalgia_note = '미로 속 추격전 — 긴장감 넘치는 한 판.' where slug = 'maze-runner' and nostalgia_note is null;
update public.games set nostalgia_note = '탱크 전투의 승부욕, 다시 불러온 아케이드.' where slug = 'tank-battle' and nostalgia_note is null;
update public.games set nostalgia_note = '우주 슈팅의 그 감성, 웨이브를 넘어서.' where slug = 'galaxy-defender' and nostalgia_note is null;
update public.games set nostalgia_note = '침략자를 막아내던 클래식 슈팅의 향수.' where slug = 'space-defender' and nostalgia_note is null;
update public.games set nostalgia_note = '버블을 터뜨리던 상쾌함, 한 발 더.' where slug = 'bubble-pop' and nostalgia_note is null;
update public.games set nostalgia_note = '논리로 채우는 9×9, 스도쿠의 정석.' where slug = 'sudoku' and nostalgia_note is null;
update public.games set nostalgia_note = '누구나 아는 틱택토, 간단하지만 중독적.' where slug = 'tic-tac-toe' and nostalgia_note is null;
update public.games set nostalgia_note = '색 순서를 기억하던 기억력 게임.' where slug = 'simon' and nostalgia_note is null;
update public.games set nostalgia_note = '한 글자씩 맞추던 단어 게임의 추억.' where slug = 'hangman' and nostalgia_note is null;
update public.games set nostalgia_note = '색을 맞추는 반사신경 테스트.' where slug = 'color-match' and nostalgia_note is null;
update public.games set nostalgia_note = '테트리스 블록을 쌓던 그 손맛.' where slug = 'tetris' and nostalgia_note is null;
update public.games set nostalgia_note = '골드를 캐내던 타이밍 게임.' where slug = 'gold-miner' and nostalgia_note is null;
update public.games set nostalgia_note = '우주를 가로지르던 슈팅 액션.' where slug = 'space-impact' and nostalgia_note is null;
update public.games set nostalgia_note = '블록을 쌓아 올리는 원터치의 긴장감.' where slug = 'stack-tower' and nostalgia_note is null;
update public.games set nostalgia_note = '같은 색 공을 정리하는 퍼즐의 만족감.' where slug = 'ball-sort' and nostalgia_note is null;
update public.games set nostalgia_note = '액체를 색별로 나누는 컬러 소트.' where slug = 'color-sort' and nostalgia_note is null;
update public.games set nostalgia_note = '페널티킥의 긴장, 골키퍼를 넘어서.' where slug = 'penalty-shootout' and nostalgia_note is null;
update public.games set nostalgia_note = '다트판을 조준하던 한 판의 집중.' where slug = 'darts' and nostalgia_note is null;
update public.games set nostalgia_note = '버블 슈터의 연쇄 폭발 쾌감.' where slug = 'bubble-shooter' and nostalgia_note is null;
update public.games set nostalgia_note = '숫자 블록을 합치는 머지 퍼즐.' where slug = 'merge-blocks' and nostalgia_note is null;
update public.games set nostalgia_note = '4목·빅4의 전략, 한 수의 승부.' where slug = 'connect4' and nostalgia_note is null;
update public.games set nostalgia_note = '돌을 뒤집는 오셀로의 두뇌 싸움.' where slug = 'reversi' and nostalgia_note is null;
update public.games set nostalgia_note = '다섯 돌을 연결하는 바둑의 긴장.' where slug = 'gomoku' and nostalgia_note is null;
update public.games set nostalgia_note = '볼링 핀을 쓰러뜨리는 스트라이크.' where slug = 'bowling' and nostalgia_note is null;
update public.games set nostalgia_note = '과녁을 조준하던 집중력 게임.' where slug = 'archery' and nostalgia_note is null;
update public.games set nostalgia_note = '슬라이딩 퍼즐로 완성하는 그림.' where slug = 'sliding-puzzle' and nostalgia_note is null;
update public.games set nostalgia_note = '두더지를 잡던 반사신경 게임.' where slug = 'whack-a-mole' and nostalgia_note is null;
update public.games set nostalgia_note = '체스보드 위 전략, 킹을 향해.' where slug = 'chess' and nostalgia_note is null;
update public.games set nostalgia_note = '체커의 대각선 점프 한 수.' where slug = 'checkers' and nostalgia_note is null;
update public.games set nostalgia_note = '조각을 맞추는 직소의 만족감.' where slug = 'jigsaw' and nostalgia_note is null;
update public.games set nostalgia_note = '만칼라 구슬 옮기기의 전략.' where slug = 'mancala' and nostalgia_note is null;
update public.games set nostalgia_note = '미니 골프 홀인원에 도전.' where slug = 'mini-golf' and nostalgia_note is null;
update public.games set nostalgia_note = '당구대 위 각도와 힘의 예술.' where slug = 'billiards' and nostalgia_note is null;
update public.games set nostalgia_note = '농구 프리스로우의 스와이프 슛.' where slug = 'basketball' and nostalgia_note is null;
update public.games set nostalgia_note = '탁구 라ally의 리듬.' where slug = 'table-tennis' and nostalgia_note is null;
update public.games set nostalgia_note = '도미노 패턴을 완성하는 퍼즐.' where slug = 'domino' and nostalgia_note is null;
update public.games set nostalgia_note = '가로세로 낱말을 채우는 crossword.' where slug = 'crossword' and nostalgia_note is null;
update public.games set nostalgia_note = '960 시작 포지션의 새로운 체스.' where slug = 'chess960' and nostalgia_note is null;
update public.games set nostalgia_note = '셔플보드 디스크를 밀어넣는 정확함.' where slug = 'shuffleboard' and nostalgia_note is null;
update public.games set nostalgia_note = '카쿠로 숫자 퍼즐의 논리.' where slug = 'kakuro' and nostalgia_note is null;
update public.games set nostalgia_note = '논리로 채우는 nonogram 그리드.' where slug = 'nonogram' and nostalgia_note is null;
update public.games set nostalgia_note = '단어를 찾아내는 워드 서치.' where slug = 'word-search' and nostalgia_note is null;
